version: '3.2'
services:
  web-client:
    build:
      context: ./clientSource
      dockerfile: ../docker/yarn.Dockerfile
    image: signalbroker-web-client:v1
    ports:
     - "8080:8080"
  envoy:
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml 
    volumes:
      - ./configuration/grpc_web/docker/envoy.yaml:/etc/envoy.yaml 
    ports:
     - "8081:8081"
     - "9901:9901"
  proxy:
    stdin_open: true
    tty: true
    image: mozgiii/docker-grpcwebproxy
    ports:
      - "8082:8080"
    command: ["/grpcwebproxy", "--backend_addr=docker.for.mac.localhost:50051", "--run_tls_server=false"]
