version: '3.2'
services:
  web-client:
    stdin_open: true
    tty: true
    image: signalbroker-web-client:v1
    environment:
      SIGNAL_SERVER_HOST_NAME: ${SIGNAL_SERVER_HOST_NAME}
    ports:
     - "8080:8080"
  envoy:
    stdin_open: true
    tty: true
    image: envoy:v1
    environment:
      SIGNAL_SERVER_HOST_NAME: ${SIGNAL_SERVER_HOST_NAME}
    ports:
     - "8081:8081"
