version: '3.2'
services:
  web-client:
    build:
      context: ./clientSource
      dockerfile: ../docker/yarn.Dockerfile
    image: signalbroker-web-client:v1
    ports:
     - "8080:8080"
    depends_on:
     - proxy
  envoy:
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml 
    volumes:
      - ./configuration/grpc_web/docker/envoy.yaml:/etc/envoy.yaml 
    ports:
     - "8081:8081"
     - "9901:9901"
  proxy:
    build:
      context: ./docker
      dockerfile: grpcwebproxy.Dockerfile
    image: grpcwebproxy
    ports:
      - "8082:8080"
    command: ./grpcwebproxy --backend_addr=${SIGNALBROKER_IP:?Add SIGNALBROKER_IP to the .env file}:50051 --run_tls_server=false --allow_all_origins --server_http_max_read_timeout 0s --server_http_max_write_timeout 0s